// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type User struct {
	ID          string    `json:"id"`
	Openid      string    `json:"openid"`
	SessionKey  string    `json:"session_key"`
	Appid       string    `json:"appid"`
	Unionid     string    `json:"unionid"`
	OpenidFrom  string    `json:"openid_from"`
	AppidFrom   string    `json:"appid_from"`
	UnionidFrom string    `json:"unionid_from"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type UsersProfile struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Nickname  string    `json:"nickname"`
	AvatarUrl string    `json:"avatar_url"`
	Gender    string    `json:"gender"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
